version: "3.5"
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "Aa123456"
    volumes:
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      binance:
        ipv4_address: 172.18.3.1

  bsc-relayer:
    image: bsc-relayer:latest
    container_name: bsc-relayer
    depends_on: ["mariadb"]
    networks:
      binance:
        ipv4_address: 172.18.3.2

  oracle-relayer:
    image: oracle-relayer:latest
    container_name: oracle-relayer
    depends_on: ["mariadb"]
    networks:
      binance:
        ipv4_address: 172.18.3.3

networks:
  binance:
    external: true
